# Generated by Django 4.1.1 on 2022-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holliyday',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
